version: "3"
services:
  my-prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
      
    # Make this container the same IP as the host
    network_mode: "host"